#You must ensure nmake.exe, cl.exe, link.exe are in system path.
#VCVARS64.bat
#Under dosbox prompt
#nmake -f Makefile.win

##########################################
CXX = cl.exe
CFLAGS = /nologo /O2 /EHsc /I. /D _WIN64 /D _CRT_SECURE_NO_DEPRECATE
TARGET = windows

all:$(TARGET)\svm-predict.exe

$(TARGET)\svm-predict.exe: svm.h svm-predict.c
	$(CXX) $(CFLAGS) svm-predict.c -Fe$(TARGET)\svm-predict.exe


clean:
	-erase /Q *.obj $(TARGET)\svm-predict.exe $(TARGET)\*.exp $(TARGET)\*.lib

